### ISSUE TITLE
Remove duplicate type syntax examples under type title

### ISSUE THREAD

**Issue by danroth27** [danroth27/DNDocsWeb#11] opened 2015-04-23 05:13 UTC
It looks like a type syntax example is being inserted just below the title with the type name:

![type title](https://cloud.githubusercontent.com/assets/1874516/7290931/a307b23c-e93c-11e4-8c22-84c80a00cf84.png)

There is a separate Syntax section on the type page, so this extra syntax example under the title seems unnecessary. Let's remove it.

**Comment by agjohnson** [comment] 2015-04-24 22:45
Duplicate of #10, addressing there.

**Closed by agjohnson** 2015-04-24 22:45 UTC
Labels: duplicate
